version: "3.1"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      MONGO_DB: url_shortener
      MONGO_COLLECTION: urls
      URL_TIME_TO_LIVE: 60 # 1 minute
volumes:
  mongo_data:
    driver: local
